#!/usr/bin/env python3
"""Regenerate sitemap.xml from the language table.

Every page in every language is a URL here, which is long past the point where
keeping the file correct by hand is realistic, and a stale sitemap is worse
than none:
<lastmod> is the one hint the major engines still honour.

    python3 scripts/build-sitemap.py            # write sitemap.xml
    python3 scripts/build-sitemap.py --check    # report drift, write nothing

<lastmod> comes from git, so it reflects when a page last actually changed
rather than when this ran. Pages that git does not know about yet fall back to
today.
"""

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from langs import LANGS, PAGES, page_url  # noqa: E402

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.py — edit the language table in
     scripts/langs.py, not this file.

     Only the pages meant to be read. works/_template/ and og-card.html are
     reachable but noindex, so listing them would contradict their own tag.

     No <changefreq> or <priority>: the major engines ignore both, and a number
     nobody reads is a number that goes wrong silently. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
"""


def last_commit_date(path: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(path)],
            capture_output=True, text=True, check=True,
            cwd=path.parent if path.parent.exists() else None,
        ).stdout.strip()
        return out or date.today().isoformat()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return date.today().isoformat()


NOINDEX_RE = re.compile(
    r'<meta[^>]*name="robots"[^>]*content="[^"]*noindex', re.I)


def is_noindex(path: Path) -> bool:
    """Whether the page asks not to be indexed.

    Listing such a page would contradict its own tag, which is the reason
    works/_template/ and og-card.html are absent from PAGES. A translation
    still waiting to be written carries the same tag but cannot be left out of
    PAGES — check-i18n.py needs it there to compare against — so the rule is
    read off the page itself rather than kept as a second list to maintain.
    The page joins the sitemap on the next run after the tag comes off.
    """
    return bool(NOINDEX_RE.search(path.read_text(encoding="utf-8")))


def build(root: Path) -> str:
    body, skipped = [], []
    for page in PAGES:
        for _, d, _, _ in LANGS:
            path = root / d / page / "index.html"
            if not path.exists():
                continue
            if is_noindex(path):
                skipped.append(str(path.relative_to(root)))
                continue
            body.append(
                f"  <url>\n"
                f"    <loc>{page_url(d, page)}</loc>\n"
                f"    <lastmod>{last_commit_date(path)}</lastmod>\n"
                f"  </url>\n"
            )
    if skipped:
        print(f"  skipped {len(skipped)} noindex page(s):")
        for s in skipped:
            print("    " + s)
    return HEADER + "".join(body) + "</urlset>\n"


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    target = root / "sitemap.xml"
    new = build(root)
    if "--check" in sys.argv:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current == new:
            print(f"OK — sitemap.xml matches ({new.count('<url>')} URLs)")
        else:
            print("sitemap.xml is out of date; run without --check")
            sys.exit(1)
    else:
        target.write_text(new, encoding="utf-8")
        print(f"wrote sitemap.xml — {new.count('<url>')} URLs")
